import type { Package, Alert, Repo, Signal } from '@/types'

function decliningHistory(start: number, end: number): number[] {
  return Array.from({ length: 90 }, (_, i) => {
    const t = i / 89
    const noise = (Math.sin(i * 0.7) * 3 + Math.cos(i * 1.3) * 2)
    return Math.max(0, Math.min(100, Math.round(start + (end - start) * t + noise)))
  })
}

function stableHistory(base: number): number[] {
  return Array.from({ length: 90 }, (_, i) => {
    const noise = Math.sin(i * 0.4) * 3 + Math.cos(i * 0.9) * 2
    return Math.max(0, Math.min(100, Math.round(base + noise)))
  })
}

function risingHistory(start: number, end: number): number[] {
  return Array.from({ length: 90 }, (_, i) => {
    const t = i / 89
    const noise = Math.sin(i * 0.5) * 2
    return Math.max(0, Math.min(100, Math.round(start + (end - start) * t + noise)))
  })
}

const sig = (value: number, trend: Signal['trend'], weight: Signal['weight']): Signal => ({
  value, trend, weight,
})

export const packages: Package[] = [
  // Critical (sps 5-19)
  {
    id: 'moment',
    name: 'moment',
    ecosystem: 'npm',
    version: '2.29.4',
    repoName: 'acme-corp/frontend',
    sps: 8,
    tier: 'critical',
    spsHistory: decliningHistory(62, 8),
    lastUpdated: '2025-11-15T10:00:00Z',
    signals: {
      commitVelocity:     sig(5,  'down', 'high'),
      maintainerActivity: sig(8,  'down', 'high'),
      funding:            sig(12, 'down', 'medium'),
      issueResolution:    sig(15, 'down', 'medium'),
      communityHealth:    sig(20, 'down', 'high'),
      securityHygiene:    sig(30, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'dayjs',   sps: 94, weeklyDownloads: 18_500_000, ecosystem: 'npm' },
      { name: 'date-fns', sps: 91, weeklyDownloads: 32_000_000, ecosystem: 'npm' },
      { name: 'luxon',    sps: 87, weeklyDownloads: 9_200_000,  ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 1240, filesAffected: 23, sprintWeeks: 2 },
  },
  {
    id: 'request',
    name: 'request',
    ecosystem: 'npm',
    version: '2.88.2',
    repoName: 'acme-corp/api-gateway',
    sps: 12,
    tier: 'critical',
    spsHistory: decliningHistory(55, 12),
    lastUpdated: '2023-09-10T08:30:00Z',
    signals: {
      commitVelocity:     sig(3,  'down', 'high'),
      maintainerActivity: sig(5,  'down', 'high'),
      funding:            sig(0,  'down', 'medium'),
      issueResolution:    sig(10, 'down', 'medium'),
      communityHealth:    sig(18, 'down', 'high'),
      securityHygiene:    sig(22, 'down', 'medium'),
    },
    recommendations: [
      { name: 'axios',   sps: 88, weeklyDownloads: 55_000_000, ecosystem: 'npm' },
      { name: 'got',     sps: 85, weeklyDownloads: 28_000_000, ecosystem: 'npm' },
      { name: 'node-fetch', sps: 82, weeklyDownloads: 45_000_000, ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 340, filesAffected: 12, sprintWeeks: 1 },
  },
  {
    id: 'left-pad',
    name: 'left-pad',
    ecosystem: 'npm',
    version: '1.3.0',
    repoName: 'acme-corp/utils',
    sps: 6,
    tier: 'critical',
    spsHistory: decliningHistory(45, 6),
    lastUpdated: '2022-03-01T00:00:00Z',
    signals: {
      commitVelocity:     sig(2,  'down', 'high'),
      maintainerActivity: sig(4,  'down', 'high'),
      funding:            sig(0,  'stable', 'medium'),
      issueResolution:    sig(8,  'down', 'medium'),
      communityHealth:    sig(12, 'down', 'high'),
      securityHygiene:    sig(15, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'String.prototype.padStart', sps: 100, weeklyDownloads: 0, ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 45, filesAffected: 3, sprintWeeks: 0.5 },
  },

  // At risk (sps 20-49)
  {
    id: 'rxjs',
    name: 'rxjs',
    ecosystem: 'npm',
    version: '6.6.7',
    repoName: 'acme-corp/frontend',
    sps: 35,
    tier: 'at-risk',
    spsHistory: decliningHistory(65, 35),
    lastUpdated: '2024-06-20T14:00:00Z',
    signals: {
      commitVelocity:     sig(28, 'down', 'high'),
      maintainerActivity: sig(32, 'down', 'high'),
      funding:            sig(40, 'stable', 'medium'),
      issueResolution:    sig(38, 'down', 'medium'),
      communityHealth:    sig(45, 'down', 'high'),
      securityHygiene:    sig(55, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'rxjs@7', sps: 72, weeklyDownloads: 48_000_000, ecosystem: 'npm' },
      { name: 'xstate',  sps: 81, weeklyDownloads: 3_200_000,  ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 890, filesAffected: 34, sprintWeeks: 3 },
  },
  {
    id: 'node-sass',
    name: 'node-sass',
    ecosystem: 'npm',
    version: '7.0.3',
    repoName: 'acme-corp/design-system',
    sps: 28,
    tier: 'at-risk',
    spsHistory: decliningHistory(58, 28),
    lastUpdated: '2024-01-10T09:00:00Z',
    signals: {
      commitVelocity:     sig(22, 'down', 'high'),
      maintainerActivity: sig(25, 'down', 'high'),
      funding:            sig(30, 'stable', 'medium'),
      issueResolution:    sig(35, 'down', 'medium'),
      communityHealth:    sig(40, 'stable', 'high'),
      securityHygiene:    sig(50, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'sass',    sps: 88, weeklyDownloads: 22_000_000, ecosystem: 'npm' },
      { name: 'postcss', sps: 95, weeklyDownloads: 60_000_000, ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 520, filesAffected: 18, sprintWeeks: 1.5 },
  },
  {
    id: 'gulp',
    name: 'gulp',
    ecosystem: 'npm',
    version: '4.0.2',
    repoName: 'acme-corp/build-tools',
    sps: 32,
    tier: 'at-risk',
    spsHistory: decliningHistory(60, 32),
    lastUpdated: '2024-03-05T11:00:00Z',
    signals: {
      commitVelocity:     sig(25, 'down', 'high'),
      maintainerActivity: sig(28, 'down', 'high'),
      funding:            sig(20, 'down', 'medium'),
      issueResolution:    sig(30, 'down', 'medium'),
      communityHealth:    sig(42, 'down', 'high'),
      securityHygiene:    sig(48, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'vite',    sps: 96, weeklyDownloads: 18_000_000, ecosystem: 'npm' },
      { name: 'esbuild', sps: 93, weeklyDownloads: 25_000_000, ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 200, filesAffected: 5, sprintWeeks: 1 },
  },
  {
    id: 'bower',
    name: 'bower',
    ecosystem: 'npm',
    version: '1.8.14',
    repoName: 'acme-corp/legacy-app',
    sps: 22,
    tier: 'at-risk',
    spsHistory: decliningHistory(55, 22),
    lastUpdated: '2022-11-20T00:00:00Z',
    signals: {
      commitVelocity:     sig(10, 'down', 'high'),
      maintainerActivity: sig(15, 'down', 'high'),
      funding:            sig(5,  'down', 'medium'),
      issueResolution:    sig(18, 'down', 'medium'),
      communityHealth:    sig(25, 'down', 'high'),
      securityHygiene:    sig(20, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'npm workspaces', sps: 100, weeklyDownloads: 0, ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 150, filesAffected: 4, sprintWeeks: 0.5 },
  },
  {
    id: 'underscore',
    name: 'underscore',
    ecosystem: 'npm',
    version: '1.13.6',
    repoName: 'acme-corp/data-pipeline',
    sps: 42,
    tier: 'at-risk',
    spsHistory: decliningHistory(70, 42),
    lastUpdated: '2024-04-15T07:00:00Z',
    signals: {
      commitVelocity:     sig(35, 'down', 'high'),
      maintainerActivity: sig(38, 'stable', 'high'),
      funding:            sig(42, 'stable', 'medium'),
      issueResolution:    sig(45, 'stable', 'medium'),
      communityHealth:    sig(50, 'down', 'high'),
      securityHygiene:    sig(60, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'lodash',  sps: 91, weeklyDownloads: 48_000_000, ecosystem: 'npm' },
      { name: 'ramda',   sps: 83, weeklyDownloads: 5_500_000,  ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 680, filesAffected: 28, sprintWeeks: 2 },
  },

  // Watch (sps 50-79)
  {
    id: 'express',
    name: 'express',
    ecosystem: 'npm',
    version: '4.18.2',
    repoName: 'acme-corp/api-gateway',
    sps: 64,
    tier: 'watch',
    spsHistory: stableHistory(67),
    lastUpdated: '2024-09-01T12:00:00Z',
    signals: {
      commitVelocity:     sig(60, 'stable', 'high'),
      maintainerActivity: sig(55, 'stable', 'high'),
      funding:            sig(65, 'stable', 'medium'),
      issueResolution:    sig(70, 'stable', 'medium'),
      communityHealth:    sig(75, 'stable', 'high'),
      securityHygiene:    sig(72, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'fastify', sps: 92, weeklyDownloads: 8_000_000, ecosystem: 'npm' },
      { name: 'hono',    sps: 89, weeklyDownloads: 2_500_000, ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 1800, filesAffected: 45, sprintWeeks: 4 },
  },
  {
    id: 'mongoose',
    name: 'mongoose',
    ecosystem: 'npm',
    version: '7.6.3',
    repoName: 'acme-corp/data-service',
    sps: 71,
    tier: 'watch',
    spsHistory: stableHistory(73),
    lastUpdated: '2024-10-15T08:00:00Z',
    signals: {
      commitVelocity:     sig(68, 'stable', 'high'),
      maintainerActivity: sig(72, 'up', 'high'),
      funding:            sig(58, 'stable', 'medium'),
      issueResolution:    sig(75, 'stable', 'medium'),
      communityHealth:    sig(80, 'up', 'high'),
      securityHygiene:    sig(76, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'prisma',  sps: 94, weeklyDownloads: 6_500_000, ecosystem: 'npm' },
      { name: 'drizzle', sps: 90, weeklyDownloads: 1_800_000, ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 2200, filesAffected: 52, sprintWeeks: 5 },
  },
  {
    id: 'passport',
    name: 'passport',
    ecosystem: 'npm',
    version: '0.7.0',
    repoName: 'acme-corp/auth-service',
    sps: 58,
    tier: 'watch',
    spsHistory: decliningHistory(75, 58),
    lastUpdated: '2024-07-20T10:00:00Z',
    signals: {
      commitVelocity:     sig(50, 'down', 'high'),
      maintainerActivity: sig(52, 'down', 'high'),
      funding:            sig(45, 'stable', 'medium'),
      issueResolution:    sig(60, 'stable', 'medium'),
      communityHealth:    sig(68, 'stable', 'high'),
      securityHygiene:    sig(65, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'lucia',    sps: 88, weeklyDownloads: 450_000,   ecosystem: 'npm' },
      { name: 'next-auth', sps: 91, weeklyDownloads: 4_200_000, ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 420, filesAffected: 14, sprintWeeks: 1.5 },
  },
  {
    id: 'winston',
    name: 'winston',
    ecosystem: 'npm',
    version: '3.11.0',
    repoName: 'acme-corp/api-gateway',
    sps: 67,
    tier: 'watch',
    spsHistory: stableHistory(68),
    lastUpdated: '2024-08-05T09:00:00Z',
    signals: {
      commitVelocity:     sig(62, 'stable', 'high'),
      maintainerActivity: sig(65, 'stable', 'high'),
      funding:            sig(55, 'stable', 'medium'),
      issueResolution:    sig(70, 'stable', 'medium'),
      communityHealth:    sig(72, 'stable', 'high'),
      securityHygiene:    sig(68, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'pino',   sps: 94, weeklyDownloads: 12_000_000, ecosystem: 'npm' },
      { name: 'consola', sps: 87, weeklyDownloads: 3_500_000,  ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 280, filesAffected: 9, sprintWeeks: 1 },
  },
  {
    id: 'nodemailer',
    name: 'nodemailer',
    ecosystem: 'npm',
    version: '6.9.7',
    repoName: 'acme-corp/notifications',
    sps: 55,
    tier: 'watch',
    spsHistory: decliningHistory(72, 55),
    lastUpdated: '2024-06-01T11:00:00Z',
    signals: {
      commitVelocity:     sig(48, 'down', 'high'),
      maintainerActivity: sig(50, 'down', 'high'),
      funding:            sig(40, 'stable', 'medium'),
      issueResolution:    sig(58, 'stable', 'medium'),
      communityHealth:    sig(62, 'stable', 'high'),
      securityHygiene:    sig(60, 'stable', 'medium'),
    },
    recommendations: [
      { name: 'resend',    sps: 92, weeklyDownloads: 800_000,   ecosystem: 'npm' },
      { name: 'sendgrid', sps: 88, weeklyDownloads: 5_200_000, ecosystem: 'npm' },
    ],
    effortEstimate: { linesImpacted: 180, filesAffected: 6, sprintWeeks: 1 },
  },

  // Healthy (sps 80-100)
  {
    id: 'lodash',
    name: 'lodash',
    ecosystem: 'npm',
    version: '4.17.21',
    repoName: 'acme-corp/frontend',
    sps: 91,
    tier: 'healthy',
    spsHistory: risingHistory(85, 91),
    lastUpdated: '2024-11-01T08:00:00Z',
    signals: {
      commitVelocity:     sig(88, 'stable', 'high'),
      maintainerActivity: sig(85, 'stable', 'high'),
      funding:            sig(90, 'up', 'medium'),
      issueResolution:    sig(92, 'stable', 'medium'),
      communityHealth:    sig(95, 'stable', 'high'),
      securityHygiene:    sig(93, 'stable', 'medium'),
    },
    recommendations: [],
    effortEstimate: { linesImpacted: 0, filesAffected: 0, sprintWeeks: 0 },
  },
  {
    id: 'axios',
    name: 'axios',
    ecosystem: 'npm',
    version: '1.6.2',
    repoName: 'acme-corp/frontend',
    sps: 88,
    tier: 'healthy',
    spsHistory: stableHistory(87),
    lastUpdated: '2024-11-10T14:00:00Z',
    signals: {
      commitVelocity:     sig(85, 'stable', 'high'),
      maintainerActivity: sig(88, 'up', 'high'),
      funding:            sig(82, 'stable', 'medium'),
      issueResolution:    sig(90, 'stable', 'medium'),
      communityHealth:    sig(92, 'stable', 'high'),
      securityHygiene:    sig(89, 'stable', 'medium'),
    },
    recommendations: [],
    effortEstimate: { linesImpacted: 0, filesAffected: 0, sprintWeeks: 0 },
  },
  {
    id: 'dayjs',
    name: 'dayjs',
    ecosystem: 'npm',
    version: '1.11.10',
    repoName: 'acme-corp/frontend',
    sps: 94,
    tier: 'healthy',
    spsHistory: risingHistory(88, 94),
    lastUpdated: '2024-11-05T09:00:00Z',
    signals: {
      commitVelocity:     sig(92, 'up', 'high'),
      maintainerActivity: sig(90, 'stable', 'high'),
      funding:            sig(88, 'stable', 'medium'),
      issueResolution:    sig(95, 'up', 'medium'),
      communityHealth:    sig(96, 'up', 'high'),
      securityHygiene:    sig(94, 'stable', 'medium'),
    },
    recommendations: [],
    effortEstimate: { linesImpacted: 0, filesAffected: 0, sprintWeeks: 0 },
  },
  {
    id: 'zod',
    name: 'zod',
    ecosystem: 'npm',
    version: '3.22.4',
    repoName: 'acme-corp/api-gateway',
    sps: 97,
    tier: 'healthy',
    spsHistory: risingHistory(90, 97),
    lastUpdated: '2024-11-12T11:00:00Z',
    signals: {
      commitVelocity:     sig(95, 'up', 'high'),
      maintainerActivity: sig(96, 'up', 'high'),
      funding:            sig(92, 'up', 'medium'),
      issueResolution:    sig(97, 'stable', 'medium'),
      communityHealth:    sig(98, 'up', 'high'),
      securityHygiene:    sig(96, 'stable', 'medium'),
    },
    recommendations: [],
    effortEstimate: { linesImpacted: 0, filesAffected: 0, sprintWeeks: 0 },
  },
  {
    id: 'chalk',
    name: 'chalk',
    ecosystem: 'npm',
    version: '5.3.0',
    repoName: 'acme-corp/build-tools',
    sps: 86,
    tier: 'healthy',
    spsHistory: stableHistory(85),
    lastUpdated: '2024-10-20T08:00:00Z',
    signals: {
      commitVelocity:     sig(84, 'stable', 'high'),
      maintainerActivity: sig(86, 'stable', 'high'),
      funding:            sig(80, 'stable', 'medium'),
      issueResolution:    sig(88, 'stable', 'medium'),
      communityHealth:    sig(90, 'stable', 'high'),
      securityHygiene:    sig(87, 'stable', 'medium'),
    },
    recommendations: [],
    effortEstimate: { linesImpacted: 0, filesAffected: 0, sprintWeeks: 0 },
  },
  {
    id: 'dotenv',
    name: 'dotenv',
    ecosystem: 'npm',
    version: '16.3.1',
    repoName: 'acme-corp/api-gateway',
    sps: 83,
    tier: 'healthy',
    spsHistory: stableHistory(82),
    lastUpdated: '2024-09-15T10:00:00Z',
    signals: {
      commitVelocity:     sig(80, 'stable', 'high'),
      maintainerActivity: sig(82, 'stable', 'high'),
      funding:            sig(78, 'stable', 'medium'),
      issueResolution:    sig(85, 'stable', 'medium'),
      communityHealth:    sig(87, 'stable', 'high'),
      securityHygiene:    sig(84, 'stable', 'medium'),
    },
    recommendations: [],
    effortEstimate: { linesImpacted: 0, filesAffected: 0, sprintWeeks: 0 },
  },
  {
    id: 'typescript',
    name: 'typescript',
    ecosystem: 'npm',
    version: '5.3.2',
    repoName: 'acme-corp/frontend',
    sps: 99,
    tier: 'healthy',
    spsHistory: risingHistory(94, 99),
    lastUpdated: '2024-11-14T12:00:00Z',
    signals: {
      commitVelocity:     sig(98, 'up', 'high'),
      maintainerActivity: sig(99, 'up', 'high'),
      funding:            sig(100, 'stable', 'medium'),
      issueResolution:    sig(97, 'stable', 'medium'),
      communityHealth:    sig(99, 'up', 'high'),
      securityHygiene:    sig(98, 'stable', 'medium'),
    },
    recommendations: [],
    effortEstimate: { linesImpacted: 0, filesAffected: 0, sprintWeeks: 0 },
  },
]

export const alerts: Alert[] = [
  {
    id: 'alert-1',
    packageId: 'moment',
    packageName: 'moment',
    spsBefore: 42,
    spsAfter: 8,
    tier: 'critical',
    firedAt: '2026-05-15T09:23:00Z',
    repos: ['acme-corp/frontend', 'acme-corp/mobile'],
    slackSent: true,
    resolved: true,
  },
  {
    id: 'alert-2',
    packageId: 'request',
    packageName: 'request',
    spsBefore: 35,
    spsAfter: 12,
    tier: 'critical',
    firedAt: '2026-05-14T14:45:00Z',
    repos: ['acme-corp/api-gateway'],
    slackSent: true,
    resolved: false,
  },
  {
    id: 'alert-3',
    packageId: 'rxjs',
    packageName: 'rxjs',
    spsBefore: 58,
    spsAfter: 35,
    tier: 'at-risk',
    firedAt: '2026-05-13T11:10:00Z',
    repos: ['acme-corp/frontend', 'acme-corp/design-system'],
    slackSent: true,
    resolved: true,
  },
  {
    id: 'alert-4',
    packageId: 'node-sass',
    packageName: 'node-sass',
    spsBefore: 50,
    spsAfter: 28,
    tier: 'at-risk',
    firedAt: '2026-05-12T16:30:00Z',
    repos: ['acme-corp/design-system'],
    slackSent: false,
    resolved: false,
  },
  {
    id: 'alert-5',
    packageId: 'bower',
    packageName: 'bower',
    spsBefore: 45,
    spsAfter: 22,
    tier: 'at-risk',
    firedAt: '2026-05-11T08:00:00Z',
    repos: ['acme-corp/legacy-app', 'acme-corp/frontend', 'acme-corp/utils'],
    slackSent: true,
    resolved: true,
  },
  {
    id: 'alert-6',
    packageId: 'gulp',
    packageName: 'gulp',
    spsBefore: 55,
    spsAfter: 32,
    tier: 'at-risk',
    firedAt: '2026-05-10T13:20:00Z',
    repos: ['acme-corp/build-tools'],
    slackSent: true,
    resolved: false,
  },
  {
    id: 'alert-7',
    packageId: 'left-pad',
    packageName: 'left-pad',
    spsBefore: 30,
    spsAfter: 6,
    tier: 'critical',
    firedAt: '2026-05-09T10:00:00Z',
    repos: ['acme-corp/utils'],
    slackSent: true,
    resolved: true,
  },
  {
    id: 'alert-8',
    packageId: 'passport',
    packageName: 'passport',
    spsBefore: 74,
    spsAfter: 58,
    tier: 'watch',
    firedAt: '2026-05-08T15:45:00Z',
    repos: ['acme-corp/auth-service'],
    slackSent: false,
    resolved: false,
  },
]

export const repos: Repo[] = [
  {
    id: 'repo-frontend',
    name: 'frontend',
    org: 'acme-corp',
    packageCount: 142,
    avgSps: 68,
    worstPackage: { name: 'moment', sps: 8, tier: 'critical' },
    connectedAt: '2026-03-10T09:00:00Z',
  },
  {
    id: 'repo-api',
    name: 'api-gateway',
    org: 'acme-corp',
    packageCount: 87,
    avgSps: 74,
    worstPackage: { name: 'request', sps: 12, tier: 'critical' },
    connectedAt: '2026-03-12T11:00:00Z',
  },
  {
    id: 'repo-legacy',
    name: 'legacy-app',
    org: 'acme-corp',
    packageCount: 38,
    avgSps: 41,
    worstPackage: { name: 'bower', sps: 22, tier: 'at-risk' },
    connectedAt: '2026-04-01T14:00:00Z',
  },
]
